- name: KVM Setup
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  become: yes

  tasks:

    - name: Install os utils
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - net-tools
        - curl
        - nano
        - tree
        - wget
        - nfs-utils
      register: output
      tags: os-utils

    - name: Install kvm
      yum: 
        name: "{{ packages }}"
      vars:
        packages:
        - qemu-kvm
        - libvirt
        - libvirt-python
        - libguestfs-tools
        - virt-install
      tags: kvm-libvirt

    - name: upgrade all packages
      yum:
        name: "*"
        state: latest

    - name: start libvirtd service
      service: name=libvirtd state=started enabled=yes
      tags: libvirtd

    - name: check virtualization technology enabled in bios
      shell: lscpu | grep -i Virtualization
      tags: kvm
      register: output
    - debug: var=output.stdout_lines

    - name: Verify kvm installation
      shell: lsmod | grep -i kvm
      tags: kvm
      register: output
    - debug: var=output.stdout_lines
